// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HousingSite.proto

package SEP3.housing_site_business_logic;

public interface GetUserByIdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SEP3.housing_site_business_logic.GetUserByIdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  long getUserId();
}
