// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HousingSite.proto

package SEP3.housing_site_business_logic;

public final class HousingSite {
  private HousingSite() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SEP3_housing_site_business_logic_GetUserByIdRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SEP3_housing_site_business_logic_GetUserByIdRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SEP3_housing_site_business_logic_GetUserByIdResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SEP3_housing_site_business_logic_GetUserByIdResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021HousingSite.proto\022 SEP3.housing_site_b" +
      "usiness_logic\"$\n\022GetUserByIdRequest\022\016\n\006u" +
      "serId\030\001 \001(\003\"O\n\023GetUserByIdResponse\022\n\n\002id" +
      "\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\017\n\007surname\030\003 \001(\t\022\r\n" +
      "\005email\030\004 \001(\t2\211\001\n\013UserService\022z\n\013getUserB" +
      "yId\0224.SEP3.housing_site_business_logic.G" +
      "etUserByIdRequest\0325.SEP3.housing_site_bu" +
      "siness_logic.GetUserByIdResponseB\002P\001b\006pr" +
      "oto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SEP3_housing_site_business_logic_GetUserByIdRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SEP3_housing_site_business_logic_GetUserByIdRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SEP3_housing_site_business_logic_GetUserByIdRequest_descriptor,
        new java.lang.String[] { "UserId", });
    internal_static_SEP3_housing_site_business_logic_GetUserByIdResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SEP3_housing_site_business_logic_GetUserByIdResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SEP3_housing_site_business_logic_GetUserByIdResponse_descriptor,
        new java.lang.String[] { "Id", "Name", "Surname", "Email", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
