// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Listing.proto

package com.group5.proto.Listing;

public final class Listing {
  private Listing() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_group5_proto_Listing_CreateHouseListingResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_group5_proto_Listing_CreateHouseListingResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rListing.proto\022\030com.group5.proto.Listin" +
      "g\"\244\002\n\031CreateHouseListingRequest\022\016\n\006stree" +
      "t\030\001 \001(\t\022\022\n\npostNumber\030\002 \001(\005\022\014\n\004city\030\003 \001(" +
      "\t\022\017\n\007houseNo\030\004 \001(\005\022\030\n\020constructionYear\030\005" +
      " \001(\005\022\023\n\013lastRebuilt\030\006 \001(\005\022\025\n\rhasInspecti" +
      "on\030\007 \001(\010\022\022\n\ngroundArea\030\010 \001(\001\022\021\n\tfloorAre" +
      "a\030\t \001(\001\022\027\n\017imageBase64Data\030\n \003(\t\022\030\n\020imag" +
      "eContentType\030\013 \003(\t\022\025\n\rimageFileName\030\014 \003(" +
      "\t\022\r\n\005price\030\r \001(\001\"\307\002\n\032CreateHouseListingR" +
      "esponse\022\n\n\002id\030\001 \001(\003\022\016\n\006street\030\002 \001(\t\022\022\n\np" +
      "ostNumber\030\003 \001(\005\022\014\n\004city\030\004 \001(\t\022\017\n\007houseNo" +
      "\030\005 \001(\005\022\030\n\020constructionYear\030\006 \001(\005\022\023\n\013last" +
      "Rebuilt\030\007 \001(\005\022\025\n\rhasInspection\030\010 \001(\010\022\022\n\n" +
      "groundArea\030\t \001(\001\022\021\n\tfloorArea\030\n \001(\001\022\027\n\017i" +
      "mageBase64Data\030\013 \003(\t\022\030\n\020imageContentType" +
      "\030\014 \003(\t\022\025\n\rimageFileName\030\r \003(\t\022\r\n\005price\030\016" +
      " \001(\001\022\024\n\014creationDate\030\017 \001(\t2\214\001\n\016ListingSe" +
      "rvice\022z\n\rcreateListing\0223.com.group5.prot" +
      "o.Listing.CreateHouseListingRequest\0324.co" +
      "m.group5.proto.Listing.CreateHouseListin" +
      "gResponseB\002P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_group5_proto_Listing_CreateHouseListingRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_CreateHouseListingRequest_descriptor,
        new java.lang.String[] { "Street", "PostNumber", "City", "HouseNo", "ConstructionYear", "LastRebuilt", "HasInspection", "GroundArea", "FloorArea", "ImageBase64Data", "ImageContentType", "ImageFileName", "Price", });
    internal_static_com_group5_proto_Listing_CreateHouseListingResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_group5_proto_Listing_CreateHouseListingResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_group5_proto_Listing_CreateHouseListingResponse_descriptor,
        new java.lang.String[] { "Id", "Street", "PostNumber", "City", "HouseNo", "ConstructionYear", "LastRebuilt", "HasInspection", "GroundArea", "FloorArea", "ImageBase64Data", "ImageContentType", "ImageFileName", "Price", "CreationDate", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
